FROM python:3.13-slim
COPY --from=docker:28-cli /usr/local/bin/docker /usr/local/bin/docker
COPY sandbox/broker.py /opt/broker.py
COPY sandbox/project_broker.py /usr/local/lib/python3.13/site-packages/project_broker.py
COPY config/general.json /opt/general.json
CMD ["python", "-I", "-B", "/opt/broker.py"]
